# Generated by Django 4.2.2 on 2023-06-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Other')])),
                ('salary', models.IntegerField()),
                ('is_staff', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='personnel.department')),
            ],
        ),
    ]
